version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_contacts.sql:/docker-entrypoint-initdb.d/create_contacts.sql
  restful-service:
    container_name: flask_restful
    image: test:2.0.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: