version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: